NUciie/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from django.conf.urls import include


from accounts.views import logout_view
from gallery import views as g
from events import views as e
from team import views as t
from home import views as h
from mailing import views as ml
from robotics import views as ro
from contactus import views as cus

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^logout/$', logout_view, name="logout"),
    url(r'^gallery/$', g.gallery, name="gallery"),
    url(r'^events/$', e.events, name="events"),
    url(r'^event_details/$',e.event_details, name="event_details"),
    url(r'^team/$', t.team, name="team"),
    url(r'^wedo/$', t.wedo, name="wedo"),
    url(r'^joinus/$', cus.joinView, name="joinus"),
    url(r'^startupform/$', cus.incubView, name="startup"),
    url(r'^$', h.home, name="home"),
    path('events/submit', e.submit, name="eventSubmit"),
    #path('<int:pk>/gen_pdf_preview/', su.serve_pdf_preview),
    url(r'^auth/', include('social_django.urls', namespace='social')),
    url(r'^mail/', ml.email),
    url(r'^startups/$', e.startups, name='startups'),
    url(r'^startup/$', e.startup),
    url(r'^robotics/$', ro.robotics,name='robotics'),
    url(r'^idea/$',cus.ideaView,name='idea')

]

urlpatterns += staticfiles_urlpatterns();

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header="NU CIIE Admin"
admin.site.site_title="NU CIIE"
admin.site.index_title="Welcome to NU CIIE"

LOGIN_REDIRECT_URL = 'home'

contactus/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.core.validators import URLValidator

# Create your models here.
class idea(models.Model):
	first_name = models.CharField(max_length=50)
	last_name  = models.CharField(max_length=50)
	email      = models.EmailField()
	enrollment_no = models.CharField(max_length=30)
	idea   = models.TextField(max_length = 4095, null=True)
	why_do_you_want_to_join_CIIE   = models.TextField(max_length = 4095, null = True, blank=True)
	join_ciie = models.BooleanField(default=True )

	def __str__(self):
		return self.first_name+' '+self.last_name

class join(models.Model):
	first_name = models.CharField(max_length=50)
	last_name  = models.CharField(max_length=50)
	email      = models.EmailField()
	enrollment_no  = models.CharField(max_length=30)
	why_do_you_want_to_join_CIIE   = models.TextField(max_length = 4095)

	def __str__(self):
		return self.first_name+' '+self.last_name

class startup(models.Model):
	org_choice = (
					('n', 'Not for Profit Organization'),
					('p', 'For Profit Organization'),
				)

	enterprise = (
					('r', 'Registered'),
					('n', 'Not Registered'),
				)

	type_impact = (
					('d', 'Direct'),
					('i', 'Indirect'),

				)

	sector_d = (
					('ai', 'Information, Communication and Entertainment'),
					('bi', 'Food, Agriculture and allied sectors'),
					('ci', 'Augmented Reality , Big data and analytics , Image Processing and Recognition ,Cloud computing, Cyber Security'),
					('di', 'Renewable energy sources , Green Technology'),
					('ei', 'Bio Informatics'),
					('fi', 'Financial Technology, NPD , Services'),
					('gi', 'Other Contemporary area'),


				)

	name_of_enterprise = models.CharField(max_length=50)
	name_of_enterpreneur  = models.CharField(max_length=50)
	email      = models.EmailField()
	phone_number  = models.CharField(primary_key=True, max_length=10, validators=[RegexValidator(r'^\d{1,10}$')])
	nationality  = models.CharField(max_length=50,default="")
	dob = models.CharField(max_length=50,default="")
	address = models.TextField("permanent address", default="")
	education = models.CharField(max_length=20, default="")
	website  = models.CharField(max_length=300, blank=True, validators=[URLValidator()],default="")
	organization_type = models.CharField(max_length=30, choices = org_choice,default="")
	is_your_enterprise = models.CharField(max_length=30, choices = enterprise,default="")
	impact = models.CharField("type of impact on social sector", max_length=30 , choices = type_impact,default="")
	nu_mentor = models.BooleanField("Have a mentor from NU ?" , default = False)
	name_of_mentor = models.CharField(blank =True , max_length = 50,default="")
	sector = models.CharField("sector for your enterprise" , max_length=300 , choices = sector_d,default="")
	mention = models.CharField("Mention your sector if not mentioned above" , blank = True, max_length= 40,default="")

	infra_resource = models.TextField("What all infrastructural resources you require ? Mention them clearly" , default="")
	special_req    = models.TextField("Mention any special requirement", default="", blank = True)
	pro_req        = models.TextField("Mention requirements of professional services/support if needed", blank = True)
	employee_space = models.TextField("Mention number of employees occupying the space", default="")
	current_space  = models.TextField("Are you currently occupying a space ? If yes give details such as area, location and monthly cost", default="" , blank = True)
	descr          = models.TextField("Description of your business products/services", default ="")
	descr_bplan    = models.TextField("Description of your b plan and attach a copy of the same" , default="")
	attachment_of_bplan = models.FileField(blank =True)
	sourc_fund  = models.TextField("Specify sources of funds",default ="", blank = True)
	benefic = models.TextField("Who will benefit from your product/Service",default ="")
	stp_benefit = models.TextField("How will your startup be benefitted from incubating at NU", default="")
	if_select = models.TextField("If selected , when will you start the incubation facility ?"  , default ="")
	other_de  = models.TextField("Any other details you want to give which will help evaluating your proposal ? " , default="", blank = True)
	Signature = models.FileField(default="#")

	def __str__(self):
		return self.name_of_enterprise

contactus/forms.py
from django import forms
from .models import idea,join,startup


class ideaForm(forms.ModelForm):
	class Meta:
		model = idea
		fields = ('first_name','last_name','email','enrollment_no','idea','join_ciie','why_do_you_want_to_join_CIIE')

	def __init__(self, *args, **kwargs):
		super(ideaForm, self).__init__(*args, **kwargs)
		self.fields['first_name'].widget.attrs['placeholder'] = 'First name'
		self.fields['last_name'].widget.attrs['placeholder'] = 'Last name'
		self.fields['email'].widget.attrs['placeholder'] = 'Email'
		self.fields['enrollment_no'].widget.attrs['placeholder'] = 'Enrollment number'
		self.fields['idea'].widget.attrs['placeholder'] = 'Your idea'
		self.fields['why_do_you_want_to_join_CIIE'].widget.attrs['placeholder'] = 'Why do you want to join CIIE'




class joinForm(forms.ModelForm):
	class Meta:
		model = join
		fields = ('first_name','last_name','email','enrollment_no','why_do_you_want_to_join_CIIE')

	def __init__(self, *args, **kwargs):
		super(joinForm, self).__init__(*args, **kwargs)
		self.fields['first_name'].widget.attrs['placeholder'] = 'First name'
		self.fields['last_name'].widget.attrs['placeholder'] = 'Last name'
		self.fields['email'].widget.attrs['placeholder'] = 'Email'
		self.fields['enrollment_no'].widget.attrs['placeholder'] = 'Enrollment number'
		self.fields['why_do_you_want_to_join_CIIE'].widget.attrs['placeholder'] = 'Why do you want to join CIIE'


class incubationForm(forms.ModelForm):
	class Meta:
		model = startup
		fields = ('name_of_enterprise',
				  'name_of_enterpreneur',
				  'email',
				  'phone_number',
				  'nationality',
				  'dob',
				  'address',
				  'education',
				  'website',
				  'organization_type',
				  'is_your_enterprise',
				  'impact',
				  'nu_mentor',
				  'name_of_mentor',
				  'sector',
				  'mention',
				  'infra_resource',
				  'special_req',
				  'pro_req',
				  'employee_space',
				  'current_space',
				  'descr',
				  'descr_bplan',
				  'attachment_of_bplan',
				  'sourc_fund',
				  'benefic',
				  'stp_benefit',
				  'if_select',
				  'other_de',
				  'Signature',
				  )
	def __init__(self, *args, **kwargs):
		super(incubationForm, self).__init__(*args, **kwargs)
		self.fields['name_of_enterprise'].widget.attrs['placeholder'] = 'Name of enterprise'
		self.fields['name_of_enterpreneur'].widget.attrs['placeholder'] = 'Name of enterpreneur'
		self.fields['email'].widget.attrs['placeholder'] = 'Email'
		self.fields['phone_number'].widget.attrs['placeholder'] = 'Phone number'
		self.fields['nationality'].widget.attrs['placeholder'] = 'Nationality'
		self.fields['dob'].widget.attrs['placeholder'] = 'Date of birth'
		self.fields['address'].widget.attrs['placeholder'] = 'Permanent Address'
		self.fields['education'].widget.attrs['placeholder'] = 'Education'
		self.fields['website'].widget.attrs['placeholder'] = 'Website'
		self.fields['organization_type'].widget.attrs['placeholder'] = 'Organization type'
		self.fields['is_your_enterprise'].widget.attrs['placeholder'] = 'Is your enterprise'
		self.fields['impact'].widget.attrs['placeholder'] = 'Type of impact on social sector'
		self.fields['nu_mentor'].widget.attrs['placeholder'] = 'Nu mentor'
		self.fields['name_of_mentor'].widget.attrs['placeholder'] = 'Have a mentor from NU ?'
		self.fields['sector'].widget.attrs['placeholder'] = 'Sector for your enterprise'
		self.fields['mention'].widget.attrs['placeholder'] = 'Mention your sector if not mentioned above'
		self.fields['infra_resource'].widget.attrs['placeholder'] = 'What all infrastructural resources you require ? Mention them clearly'
		self.fields['special_req'].widget.attrs['placeholder'] = 'Mention any special requirement'
		self.fields['pro_req'].widget.attrs['placeholder'] = 'Mention requirements of professional services/support if needed'
		self.fields['employee_space'].widget.attrs['placeholder'] = 'Mention number of employees occupying the space'
		self.fields['current_space'].widget.attrs['placeholder'] = 'Are you currently occupying a space ? If yes give details such as area, location and monthly cost'
		self.fields['descr'].widget.attrs['placeholder'] = 'Description of your business products/services'
		self.fields['descr_bplan'].widget.attrs['placeholder'] = 'Description of your b plan and attach a copy of the same'
		self.fields['attachment_of_bplan'].widget.attrs['placeholder'] = 'Attachment of bplan'
		self.fields['sourc_fund'].widget.attrs['placeholder'] = 'Specify sources of funds'
		self.fields['benefic'].widget.attrs['placeholder'] = 'Who will benefit from your product/Service'
		self.fields['stp_benefit'].widget.attrs['placeholder'] = 'How will your startup be benefitted from incubating at NU'
		self.fields['if_select'].widget.attrs['placeholder'] = 'If selected , when will you start the incubation facility ?'
		self.fields['other_de'].widget.attrs['placeholder'] = 'Any other details you want to give which will help evaluating your proposal?'
		self.fields['Signature'].widget.attrs['placeholder'] = 'Signature'

contactus/views.py
from django.shortcuts import render
from .models import idea,join, startup
from django.shortcuts import redirect
import sweetify
from NUciie.utils import render_to_pdf 
from django.template.loader import get_template
from django.http import HttpResponse



from .forms import ideaForm, joinForm, incubationForm
# Create your views here.
def ideaView(request):
	template="idea.html"

	if request.method == "POST":
		form = ideaForm(request.POST)
		if form.is_valid():
			form.save()
			sweetify.success(request, 'Your Idea was submitted', text='', persistent='Ok')
			return redirect('/idea')

	else:
		form = ideaForm()

	context = {
		'form' : form ,
	}			

	return render(request, template, context)

def joinView(request):
	template="join.html"

	if request.method == "POST":
		form = joinForm(request.POST)

		if form.is_valid():
			form.save()
			sweetify.success(request, 'Your request was submitted', text='', persistent='Ok')
			return redirect('/joinus')

	else:
		form = joinForm()

	context = {
		'form' : form 
	}			

	return render(request, template, context)

def incubView(request):
	template="startup.html"

	if request.method == "POST":
		form = incubationForm(request.POST)

		if form.is_valid():
			form.save()
			sweetify.success(request, 'Your application was submitted', text='', persistent='Ok')
			return redirect('/startupform')

	else:
		form = incubationForm()

	context = {
		'form' : form ,
	}			

	return render(request, template, context)


def joinPDF(request, object_id):
	obj=join.objects.get(pk=object_id)

	template = get_template('pdfjoin.html')
	html = template.render({'obj':obj})

	pdf = render_to_pdf('pdfjoin.html',{'obj':obj})
	if pdf:
		response = HttpResponse(pdf, content_type='application/pdf')
		filename = obj.first_name+".pdf"
		content = "inline; filename=%s" %(filename)
		download = request.GET.get("download")
		if download:
			content = "attachment; filename=%s" %(filename)
		response['Content-Disposition'] = content
		return response
	return HttpResponse("Not found")

def ideaPDF(request, object_id):
	obj=idea.objects.get(pk=object_id)

	template = get_template('pdfIdea.html')
	html = template.render({'obj':obj})

	pdf = render_to_pdf('pdfIdea.html',{'obj':obj})
	if pdf:
		response = HttpResponse(pdf, content_type='application/pdf')
		filename = obj.first_name+".pdf"
		content = "inline; filename=%s" %(filename)
		download = request.GET.get("download")
		if download:
			content = "attachment; filename=%s" %(filename)
		response['Content-Disposition'] = content
		return response
	return HttpResponse("Not found")

def startupPDF(request, object_id):
	obj=startup.objects.get(name_of_enterprise=object_id)
	template = get_template('pdfstartup.html')
	html = template.render({'obj':obj})

	pdf = render_to_pdf('pdfstartup.html',{'obj':obj})
	if pdf:
		response = HttpResponse(pdf, content_type='application/pdf')
		filename = obj.name_of_enterprise+".pdf"
		content = "inline; filename=%s" %(filename)
		download = request.GET.get("download")
		if download:
			content = "attachment; filename=%s" %(filename)
		response['Content-Disposition'] = content
		return response
	return HttpResponse("Not found")

contactus/templates/idea.html
  {% extends 'base.html' %}
{% load static from staticfiles %}

{% block extra_css %}
     <script src="https://www.google.com/recaptcha/api.js" async defer></script>

  <link rel="stylesheet" href="{% static 'joinus.css' %}">
  <style>
    #content {
    max-height: 0;
    overflow: hidden;
    transition: max-height 0.2s ease-out;
    }

    #id_join_ciie{
      display: none;
    }
  </style>
{% endblock %}

{% block content %}
<div class="login-page">
  <div class="form">
    <h2>Submit Your Idea!</h2>
    {{ form.non_field_errors }}
    <form class='login-form' method = "POST">
    {% csrf_token %}
    <div class="fieldWrapper">
      {{ form.first_name.errors }}
      {{ form.first_name }}
      {{ form.last_name.errors }}
      {{ form.last_name }}
      {{ form.email.errors }}
      {{ form.email }}
      {{ form.enrollment_no.errors }}
      {{ form.enrollment_no }}
      {{ form.idea.errors }}
      {{ form.idea }}
      <h2 for="{{ form.join_ciie.id_for_label }}">Join CIIE?</h2>
      <div class="btn-group" style="width: 100%">
        <button type="button" id="yes" >Yes</button>
        <button type="button" id="no"" style="background-color: #B1351A">No</button>
      </div><br>
            <div class="g-recaptcha" data-sitekey="6LdC058UAAAAAKYRRfXqwcI2BWhLmfTeC0g4sT_u"></div>

      {{ form.join_ciie }}
      <div id="content">
        {{ form.why_do_you_want_to_join_CIIE.errors }}
        {{ form.why_do_you_want_to_join_CIIE }}
      </div>  
    </div>
    <button class="btn" > Submit form </button>
  </form>
  </div>
</div>

<script>

var content = document.getElementById("content");

$("#yes").click(function(){
  document.getElementById("id_join_ciie").checked = true;
  content.style.maxHeight = content.scrollHeight + "px";
  $("#no").css('background-color', '#821618');
  $(this).css('background-color', '#B1351A');
});

$("#no").click(function(){
  document.getElementById("id_join_ciie").checked = false;
  content.style.maxHeight = null;
  $("#yes").css('background-color', '#821618');
  $(this).css('background-color', '#B1351A');
});

</script>


{% endblock %}

contactus/templates/join.html
{% extends "base.html" %}
{% load static from staticfiles %}

{% block extra_css%}
     <script src="https://www.google.com/recaptcha/api.js" async defer></script>

  <link rel="stylesheet" href="{% static 'joinus.css' %}">
{% endblock %}

{% block content %}
<div class="login-page">
	<div class="form">
		<h2 >JOIN US ! </h2>
		<form class='login-form' method = "POST" >
			{% csrf_token %}
			{{form.as_p}}
			<br>
            <div class="g-recaptcha" data-sitekey="6LdC058UAAAAAKYRRfXqwcI2BWhLmfTeC0g4sT_u"></div>

			<button type="submit"> SEND </button>
		</form>
	</div>
</div>

{% endblock %}

contactus/templates/pdfidea.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<title>no</title>
	<style type="text/css">
    body {
    background-color: lightblue;
  }
	</style>
</head>
<body>
  {{obj.first_name}} {{obj.last_name}}<br>
  {{obj.email}}<br>
  {{obj.enrollment_no}}<br>
  {{obj.idea}}<br>
  {{obj.why_do_you_want_to_join_CIIE}}
</body>
</html>

contactus/templates/pdfjoin.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<title>no</title>
	<style type="text/css">
    body {
    background-color: lightblue;
  }
	</style>
</head>
<body>
  {{obj.first_name}} {{obj.last_name}}<br>
  {{obj.email}}<br>
  {{obj.enrollment_no}}<br>
  {{obj.why_do_you_want_to_join_CIIE}}
</body>
</html>

contactus/templates/pdfstartup.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<title>no</title>
	<style type="text/css">
    body {
    background-color: lightblue;
  }
	</style>
</head>
<body>
  {{obj.name_of_enterprise}}<br>
  {{obj.name_of_enterpreneur}}<br>
  {{obj.email}}<br>
  {{obj.phone_number}}<br>
  {{obj.nationality}}<br>
  {{obj.dob}}<br>
  {{obj.address}}<br>
  {{obj.education}}<br>
  {{obj.website}}<br>
  {{obj.organization_type}}<br>
  {{obj.is_your_enterprise}}<br>
  {{obj.impact}}<br>
  {{obj.name_of_mentor}}<br>
  {{obj.sector}}<br>
  {{obj.mention}}<br>
  {{obj.infra_resource}}<br>
  {{obj.special_req}}
</html>

contactus/templates/startup.html
{% extends "base.html" %}
{% load static from staticfiles %}

{% block extra_css%}
     <script src="https://www.google.com/recaptcha/api.js" async defer></script>

  <link rel="stylesheet" href="{% static 'joinus.css' %}">
  <script src="{% static 'parsley.js' %}"></script>
  <style type="text/css">

  </style>
{% endblock %}

{% block content %}


<div class="login-page">
	<div class="form">
	<form class="login-form" method = "POST" data-validate="parsley">
		<h2>Application Form For Incubation at NIIT University </h2>
		{% csrf_token %}
    <div class="tab" data-validate="parsley">
		  {{form.name_of_enterprise}}
      {{form.name_of_enterprise.error}}
      {{form.name_of_enterpreneur}}
      {{form.name_of_enterpreneur.error}}
      {{form.email}}
      {{form.email.error}}
      {{form.phone_number}}
      {{form.phone_number.error}}
      {{form.nationality}}
      {{form.nationality.error}}
      {{form.dob}}
      {{form.dob.error}}
      <button type="button" class="next">Next</button>
    </div>
    <div class="tab"> 
      {{form.address}}
      {{form.address.error}}
      {{form.education}}
      {{form.education.error}}
      {{form.website}}
      {{form.website.error}}
      <div class="btn-group" style="width: 100%">
        <button type="button" class="previous" style="background-color: #B1351A">Previous</button>
        <button type="button" class="next" >Next</button>
      </div>
    </div>
    <div class="tab"> 
      {{form.organization_type}}
      {{form.organization_type.error}}
      {{form.is_your_enterprise}}
      {{form.is_your_enterprise.error}}
      {{form.impact}}
      {{form.impact.error}}
      {{form.nu_mentor}}
      {{form.nu_mentor.error}}
      {{form.name_of_mentor}}
      {{form.name_of_mentor.error}}
      {{form.sector}}
      {{form.sector.error}}
      {{form.mention}}
      {{form.mention.error}}

    <div class="btn-group" style="width: 100%">
        <button type="button" class="previous" style="background-color: #B1351A">Previous</button>
        <button type="button" class="next" >Next</button>
      </div>
    </div>
    <div class="tab">
      {{form.infra_resource}}
      {{form.infra_resource.error}}
      {{form.special_req}}
      {{form.special_req.error}}
      {{form.pro_req}}
      {{form.pro_req.error}}
      <div class="btn-group" style="width: 100%">
        <button type="button" class="previous" style="background-color: #B1351A">Previous</button>
        <button type="button" class="next" >Next</button>
      </div>
    </div>
    <div class="tab"> 
      {{form.employee_space}}
      {{form.employee_space.error}}
      {{form.current_space}}
      {{form.current_space.error}}
      {{form.descr}}
      {{form.descr.error}}

            <div class="btn-group" style="width: 100%">
        <button type="button" class="previous" style="background-color: #B1351A">Previous</button>
        <button type="button" class="next" >Next</button>
      </div>
    </div>
    <div class="tab">
      {{form.descr_bplan}}
      {{form.descr_bplan.error}}
      {{form.attachment_of_bplan}}
      {{form.attachment_of_bplan.error}}
      {{form.sourc_fund}}
      {{form.sourc_fund.error}}
      <div class="btn-group" style="width: 100%">
        <button type="button" class="previous" style="background-color: #B1351A">Previous</button>
        <button type="button" class="next" >Next</button>
      </div>
    </div>
    <div class="tab"> 
      {{form.benefic}}
      {{form.benefic.error}}
      {{form.stp_benefit}}
      {{form.stp_benefit.error}}
            {{form.if_select}}
      {{form.if_select.error}}
      <div class="btn-group" style="width: 100%">
        <button type="button" class="previous" style="background-color: #B1351A">Previous</button>
        <button type="button" class="next" >Next</button>
      </div>
    </div>
    <div class="tab"> 
      {{form.other_de}}
      {{form.other_de.error}}
      {{form.Signature}}
      {{form.Signature.error}}
      <div class="btn-group" style="width: 100%">
        <button type="button" class="previous" style="background-color: #B1351A">Previous</button>

      <br>
            <div class="g-recaptcha" data-sitekey="6LdC058UAAAAAKYRRfXqwcI2BWhLmfTeC0g4sT_u"></div>
        <button type="submit"> SEND </button>
      </div>
  </div>
  <div style="text-align:center;margin-top:40px;">
  <span class="step"></span>
  <span class="step"></span>
  <span class="step"></span>
  <span class="step"></span>
  <span class="step"></span>
  <span class="step"></span>
  <span class="step"></span>
  <span class="step"></span>
</div>
	</form>
	</div>
</div>

<script type="text/javascript">
  var $sections = $('.tab');
  $sections.each(function(index, section) {
    $(section).find(':input').attr('data-parsley-group', 'block-' + index);
  });


  var tabs= document.getElementsByClassName('tab')
  var step= document.getElementsByClassName('step')
  var i=0;
  tabs[i].style.display="block";
  step[i].style.opacity="1"
  $(".next").click(function(){
      $('form').parsley().whenValidate({
        group: 'block-' + i
        }).done(function() {
            tabs[i].style.display="none";
            step[i].style.opacity="0.1"
            i++;
            tabs[i].style.display="block";
            step[i].style.opacity="1"
            $("html, body").animate({ scrollTop: 0 }, "slow");
      });
    });

  $(".previous").click(function(){
      tabs[i].style.display="none";
      step[i].style.opacity="0.1"
      i--;
      tabs[i].style.display="block";
      step[i].style.opacity="1"
    });
</script>


{% endblock %}